test(config): initialize firebase auth session persistence suite (#178)
* test(config): initialize firebase auth session persistence suite

Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Action:
- Scaffold initial test suite `SessionPersistence.integration.test.tsx`
  as the foundational verification for Firebase Authentication
  Persistence using Firebase Emulators Suite within a jsdom ecosystem so
  Firebase Auth can read/write to a virtual browser storage environment.

- Add dependencies to the global mock registry `jest.setup.js` and
  whitelisting/transformations to `jest.config.js`.

- Map `firebase/app` and `firebase/auth` modules to Common JS
  Entrypoints in `jest.config.js`.

- Standardize @layout alias in tsconfig

- Mock `expo-constants` for firebase init configuration dummy values and
  `expo-splash-screen`

- Stub `expo-router` to prevent jsdom breaking heavy UI imports, and
  mock `firebase-auth` at the test-level to bypass react-native
  dependencies

Result: A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established. Our
current status is mocking `app/_layout` imports, specifically
`layouts/js-stack.tsx` to clear jests error-cascade.

Related: #111 #114 #171

* test(config): initialize firebase auth session persistence suite

Context: Scaffolding `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD) is ongoing.

Action:
- Continue scaffolding initial test suite
  `SessionPersistence.integration.test.tsx` as the foundational
  verification for Firebase Authentication Persistence using Firebase
  Emulators Suite within a jsdom ecosystem so Firebase Auth can
  read/write to a virtual browser storage environment.

- Add dependencies to the global mock registry `jest.setup.js` and
  whitelisting/transformations to `jest.config.js`.

- Abstract jsdom mocks to a `@utils/jsdomMocks.tsx`

- Mock `expo-updates` `expo-modules-core`

Result: A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established. Our
current status is continuing mocking `app/_layout` imports, specifically
`layouts/js-stack.tsx` to clear jests error-cascade.

Related: #111 #114 #171

* test(config): initialize firebase auth session persistence suite

Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Action:

- Reorganize `SessionPersistence.integration.test.tsx` imports so they
  are before function calls

Result: Clears linting warning: Import in body of module; reorder to top

A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established. Our
current status is mocking `app/_layout` imports, specifically
`layouts/js-stack.tsx` to clear jests error-cascade.

Related: #111 #114 #171

* test(config): initialize firebase auth session persistence suite

Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Action: Have jest transform `@sentry/react-native`

Result: No immediate advantages--preventative.

A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established. Our
current status is mocking `app/_layout` imports, specifically
`layouts/js-stack.tsx` to clear jests error-cascade.

Related: #111 #114 #171

* test(config): initialize firebase auth session persistence suite

Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Subcontext:
The Error: `INTERNAL ASSERTION FAILED: Could not find fetch
implementation, make sure you call FetchProvider.initialize() with an
appropriate polyfill` is due to the Node.js global `fetch` API not
available to `@firebase/auth`

Action: Inject global `whatwg-fetch` polyfill primitives for jsdom

Result: Polyfill injected; `@firebase/auth` bundle finds `fetch`
implmentation.

A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established. Our
current status is mocking `app/_layout` imports, specifically
`layouts/js-stack.tsx` to clear jests error-cascade.

Related: #111 #114 #171

* test(config): initialize firebase auth session persistence suite

Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Subcontext:
- `auth/network-request-failed` config warning
- `signInWithEmailAndPassword` call is throwing a network failure
- Test logs display `---=== NOT USING FIREBASE EMULATORS ===---`

Local .env variable: `EXPO_PUBLIC_USE_EMULATOR = true` not being read or
read as `undefined` triggering auth crash.

Action: Set `EXPO_PUBLIC_USE_EMULATOR` to `true` withing test file.

Result: Test connecting to Firebase Auth emulator.

A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established. Our
current status is mocking `app/_layout` imports, specifically
`layouts/js-stack.tsx` to clear jests error-cascade.

Related: #111 #114 #171

* test(config): initialize firebase auth session persistence suite

Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Subcontext: Requiring actual `expo-modules-core` package triggers
console warning `The "EXNativeModulesProxy" native module is not
exported through NativeModules...` because the module searches for
React Natives native device bridge in a `jsdom` environment

Action: Stub out the entire `actual` module.

Result: Warning cleared. The `expo-modules-core` packages internal
native linking check is skipped.

A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established. Our
current status is mocking `app/_layout` imports, specifically
`layouts/js-stack.tsx` to clear jests error-cascade.

Related: #111 #114 #171

* test(config): initialize firebase auth session persistence suite

Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Subcontext: Font loading engine throws `useFonts` warning `TypeError: (0
, _expoModulesCore.requireOptionalNativeModule) is not a function` due
to `jsdom` virtual browser environment failing to load non-existent
asset.

Action: Mock `expo-font` to report fonts are loaded.

Result: Warning removed; Expo Font no longer trying to load `.ttf` from
simulated DOM (jsdom)

A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established. Our
current status is mocking `app/_layout` imports, specifically
`layouts/js-stack.tsx` to clear jests error-cascade.

Related: #111 #114 #171

* test(config): initialize firebase auth session persistence suite

Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Subcontext: Screen Transition animations from `@react-navigation/stack`
throwing `TypeError: Cannot read properties of undefined (reading
'out')` (...'out' is from `Easing.out`) due to `jsdom` virtual browser
framework. Note that Screen Transition Animations are not in our
Authentication Redirection testing scope.

Action: Add custom `JsStack` layout wrapper stub to bypass animations.

Result: Error removed; broken `@react-navigation/stack` native
animations bypassed for test suite. Simple React container component
will be rendered in `jsdom` instead.

A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established. Our
current status is mocking `app/_layout` imports, specifically
`layouts/js-stack.tsx` to clear jests error-cascade.

Related: #111 #114 #171

* test(config): initialize firebase auth session persistence suite

Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Subcontext: 5000ms handing timeout on `GREEN: should keep
unauthenticated users on the public stack` test case due to testing
configuration `waitFor` retry loop waiting forever for a function NOT to
be called.

Action: Remove `await waitFor` recurring retry loop

Result: GREEN test passes after evaluating assertion synchronously right
after render pass

A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established. Our
current status is mocking `app/_layout` imports, specifically
`layouts/js-stack.tsx` to clear jests error-cascade.

Related: #111 #114 #171

* test(config): initialize firebase auth session persistence suite

Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Subcontext: Receiving a timeout error due to the
`signInWithEmailAndPassword` requiring a real clock in the test.

Action: Use real timers instead of jests fake timers.

Result: Error resolved; `signInWithEmailAndPassword` now reaches
Firebase emulator, `waitFor` no longer stalling.

Related: #111 #114 #171

* test(config): initialize firebase auth session persistence suite

Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Subcontext: Test should account for unauthenticated user already at the
login screen, in which case we do not redirect.

Action: Inject mock segments

Result: Unblocks the test assertion logic that an unauthenticated user
sitting at the login screen is not rerouted to the same screen.

A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established.

Related: #111 #114 #171

* test(config): conclude firebase auth session persistence suite

Context: Concluding `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Subcontext: Wrap up testing logic for assertions against Firebase Auth
Persistence logic.

Action:
- `beforeEach`/`afterEach` test tear-down logic isolates all tests by
  clearing mock segments and scrubbing Firebase emulator user accounts.

- New test asserting unauthenticated users are routed to /login is
  active.

Result (Traceability to 5a54dd5): Test bed is clean and fully scaffolded
unblocking `_layout.tsx` `onAuthStateChanged()` entrypoint logic for
routing users depending on session authentication and persistence.

These tests are intentional **Red Failures** used to assert against
Firebase Session Persistence Feature. PR #178 will be concluded when
these tests are passing.

Related: #111 #114 #171

* build(metro): reference firebase config using environment variables

- prefix non-sensitive environment variables `EXPO_PUBLIC_*`
- `firebaseConfig` config object: all properties use env variables
- `jest.setup.js`:
    - Mock `expo-constants` disabled (unused)
    - Environment variable mocks for tests included
- `app.config.ts` no longer needs to store our Firebase creds, no longer
  using `expo-constants` (.env vars are non-sensitive, store sensitive
  credentials in .env.local)

Related: #26 #35 #47 #111 #114 #171

* feat(auth): conclude firebase auth peristence with verification

Context: Concluding `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with passing authenticated user
redirect tests for PR #178.

Action: Implement Auth Guard with Firebase `onAuthStateChanged` listener
at `app/_layout.tsx` entrypoint to route users depending on current
route and authentication status.

Result (Traceability to 8b8e157): Firebase Auth persistence suite is
functional and verified **GREEN Passing** with Auth Guard feature
implementation. This concludes the intial TDD test bed scaffolding for
future Firebase Auth verification testing and feature implementation.

Related: #111 #114 #171