Display Snackbar on successful category creation
- Maximum width of 400 for default Snackbars

Error thrown from `OverlayProvider` on Snackbar dismissal:

  Error: Invalid prop `compact` supplied to `React.Fragment`

  Documentation on `compact` can be found in RNP Button component docs:

  > compact
  > Type: boolean
  >
  > Use a compact look, useful for text buttons in a row.

  https://callstack.github.io/react-native-paper/docs/components/Button/#compact

  What the hell is it, and why is it screwing with me?

  `compact` is responsible for using a "compact look useful for text
  buttons in a row" (boolean value). According to Google,
  `<Dialog.Actions>` recursively clones the components you place within
  it and passes the `compact` prop to each to apply this "compact"
  feature if needed.

  Solution:

  The fragment located in the `actions` property of `DialogConfig`
  object -- The property responsible for showing a list of actions in a
  Dialog (E.g., "Load Material", "Skip" buttons) -- has been replaced
  with a `View` to accept the prop and appease the Error Police.

  Robust Solution (TODO):

  A Failsafe should be added to the `OverlayProvider` to assure a
  `React.Fragment` is always wrapped in a `View` component.

Related:

  Create `LoadMaterialCategory` component #98
  #137  Create `Dialog` component
  #130  Wrap Contexts in Provider components
  Error: Invalid prop compact supplied to React.Fragment #141