test(config): initialize firebase auth session persistence suite
Context: Commencing `SessionPersistence.integration.test.tsx` for
testing Firebase Auth Persistence with a failing authenticated user
redirect and require mocks for the Jest testing setup and initial
failing test (TDD).

Subcontext: Font loading engine throws `useFonts` warning `TypeError: (0
, _expoModulesCore.requireOptionalNativeModule) is not a function` due
to `jsdom` virtual browser environment failing to load non-existent
asset.

Action: Mock `expo-font` to report fonts are loaded.

Result: Warning removed; Expo Font no longer trying to load `.ttf` from
simulated DOM (jsdom)

A few mocks have been implemented and are functioning correctly
with more to implement before our **Red Falure** is established. Our
current status is mocking `app/_layout` imports, specifically
`layouts/js-stack.tsx` to clear jests error-cascade.

Related: #111 #114 #171